name: commitfiles
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Modify value # Tried to modify the files based on existing testfile.txt
        run: |
          echo 'm' >> testfile.txt
      - name: move to dir # Move the generated files into output folder
        run: |
          yes| cp -rf testfile.txt ./
      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "peter.schnoor@hellmedia.de"
          git config --local user.name "oberbayer"
          git commit -m "Add changes"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
